site_name: Django APIRouter
site_description: Django API Router
site_author: Anton Ruhlov

theme:
  name: material
  palette:
    scheme: default
    primary: green

plugins:
  - search
  - mkdocstrings

repo_name: antonrh/django-apirouter
repo_url: https://github.com/antonrh/django-apirouter
edit_uri: ""

nav:
- Introduction: index.md
- Routing: routing.md
- Request: request.md
- Response: response.md
- Decorators: decorators.md
- OpenAPI: openapi.md
- Settings: settings.md

markdown_extensions:
  - codehilite

extra_css:
  - css/extra.css